In [1]:
import random
import polars as pl
from pathlib import Path
import json

In [2]:
nlg_ds = pl.read_csv('../../data/recipenlg/RecipeNLG_dataset.csv')#,  n_rows=1000)
nlg_ds = nlg_ds.with_columns(pl.col("ingredients").str.json_decode())
nlg_ds = nlg_ds.with_columns(pl.col("directions").str.json_decode())
nlg_ds = nlg_ds.with_columns(pl.arange(pl.len()).alias("index"))

In [3]:
import random
random.seed(123)
eval_data_idx = random.sample(range(0,nlg_ds.shape[0]), k=1000)

### The above code was used to generate data, but now since it is generated, we use the exact indexes in the generated data

In [4]:
with open("../../data/eval_data/eval_data.json", 'r') as f:
    read_idx_ds = pl.read_json(f)

In [5]:
eval_data_idx = list(read_idx_ds['index'])

In [6]:
out_ds = nlg_ds.filter(pl.col("index").is_in(eval_data_idx))

In [7]:
# Don't accidentally overwrite
#with open("../../data/eval_data/eval_data.json", "w") as f:
    #json.dump(out_ds.select('index', 'title', 'ingredients').to_dicts(), f, indent=2)

In [8]:
with open("../../data/eval_data/processed_data.json", "r") as f:
    processed_ds = pl.read_json(f)

In [9]:
processed_ds.head()

shape: (5, 7)
┌───────┬───────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┐
│ index ┆ title         ┆ ingredients  ┆ google_searc ┆ main_food_it ┆ important_in ┆ google_searc │
│ ---   ┆ ---           ┆ ---          ┆ h_query      ┆ ems_and_prep ┆ gredients_fo ┆ h_query_proc │
│ i64   ┆ str           ┆ list[str]    ┆ ---          ┆ aratio…      ┆ r_sear…      ┆ essed        │
│       ┆               ┆              ┆ str          ┆ ---          ┆ ---          ┆ ---          │
│       ┆               ┆              ┆              ┆ list[str]    ┆ list[str]    ┆ struct[2]    │
╞═══════╪═══════════════╪══════════════╪══════════════╪══════════════╪══════════════╪══════════════╡
│ 1461  ┆ Apricot Cake  ┆ ["2 c.       ┆ apricot cake ┆ ["sugar",    ┆ ["apricot    ┆ {"Apricot    │
│       ┆               ┆ sugar", "4   ┆ recipe with  ┆ "eggs", …    ┆ baby food",  ┆ Cake",["baby │
│       ┆               ┆ eggs", …     ┆ baby …       ┆ "chopped n…  ┆ "flour",…    ┆ food", …     │
│       ┆               ┆ "1/…         ┆              ┆              ┆              ┆              │
│ 1490  ┆ Angel         ┆ ["1 c.       ┆ angel        ┆ ["miniature  ┆ ["marshmallo ┆ {"Angel Deli │
│       ┆ Delights      ┆ miniature    ┆ delights     ┆ marshmallows ┆ ws",         ┆ ghts",["mars │
│       ┆               ┆ marshmallows ┆ recipe with  ┆ ", "br…      ┆ "pretzels",  ┆ hmallo…      │
│       ┆               ┆ "…           ┆ mar…         ┆              ┆ ……           ┆              │
│ 3374  ┆ Savory        ┆ ["1 lb. bulk ┆ sausage and  ┆ ["bulk pork  ┆ ["pork       ┆ {"Savory     │
│       ┆ Sausage       ┆ pork         ┆ rice         ┆ sausage",    ┆ sausage",    ┆ Sausage Cass │
│       ┆ Casserole     ┆ sausage",    ┆ casserole    ┆ "uncooke…    ┆ "rice", …    ┆ erole",["…   │
│       ┆               ┆ "1…          ┆ wit…         ┆              ┆ "al…         ┆              │
│ 7006  ┆ Zemakove      ┆ ["2 c.       ┆ potato       ┆ ["mashed     ┆ ["mashed     ┆ {"Zemakove   │
│       ┆ Knedliky A    ┆ mashed       ┆ dumplings    ┆ potatoes",   ┆ potatoes",   ┆ Knedliky A   │
│       ┆ Kysele Zel…   ┆ potatoes",   ┆ with         ┆ "salt", … …  ┆ "sauerkrau…  ┆ Kysele Z…    │
│       ┆               ┆ "1/2 …       ┆ sauerkra…    ┆              ┆              ┆              │
│ 9957  ┆ Scalloped     ┆ ["1/4 c.     ┆ scalloped    ┆ ["sugar",    ┆ ["sweet      ┆ {"Scalloped  │
│       ┆ Sweet         ┆ sugar", "1/2 ┆ sweet        ┆ "cinnamon",  ┆ potatoes",   ┆ Sweet Potato │
│       ┆ Potatoes      ┆ tsp. cin…    ┆ potatoes and ┆ … "marga…    ┆ "apples", "… ┆ es",["…      │
│       ┆               ┆              ┆ a…           ┆              ┆              ┆              │
└───────┴───────────────┴──────────────┴──────────────┴──────────────┴──────────────┴──────────────┘

In [10]:
human_eval_data_idx = random.sample(eval_data_idx, k=50)

In [11]:
human_eval_ds = processed_ds.filter(pl.col("index").is_in(human_eval_data_idx))

In [12]:
human_eval_ds.head()

shape: (5, 7)
┌────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┐
│ index  ┆ title        ┆ ingredients  ┆ google_searc ┆ main_food_it ┆ important_in ┆ google_searc │
│ ---    ┆ ---          ┆ ---          ┆ h_query      ┆ ems_and_prep ┆ gredients_fo ┆ h_query_proc │
│ i64    ┆ str          ┆ list[str]    ┆ ---          ┆ aratio…      ┆ r_sear…      ┆ essed        │
│        ┆              ┆              ┆ str          ┆ ---          ┆ ---          ┆ ---          │
│        ┆              ┆              ┆              ┆ list[str]    ┆ list[str]    ┆ struct[2]    │
╞════════╪══════════════╪══════════════╪══════════════╪══════════════╪══════════════╪══════════════╡
│ 42580  ┆ Asparagus-Cu ┆ ["1 (3 oz.)  ┆ asparagus    ┆ ["lime       ┆ ["lime       ┆ {"Asparagus- │
│        ┆ cumber Mold  ┆ pkg. lime    ┆ cucumber     ┆ flavored     ┆ gelatin",    ┆ Cucumber     │
│        ┆              ┆ flavored…    ┆ jello mold … ┆ gelatin",    ┆ "cream of    ┆ Mold",["j…   │
│        ┆              ┆              ┆              ┆ "boi…        ┆ asp…         ┆              │
│ 89070  ┆ Picnic Beans ┆ ["1 (16 oz.) ┆ picnic beans ┆ ["kidney     ┆ ["kidney     ┆ {"Picnic Bea │
│        ┆              ┆ can kidney   ┆ recipe with  ┆ beans",      ┆ beans",      ┆ ns",["bacon" │
│        ┆              ┆ beans"…      ┆ bacon…       ┆ "pork and    ┆ "pork and    ┆ , "kid…      │
│        ┆              ┆              ┆              ┆ bea…         ┆ bea…         ┆              │
│ 102340 ┆ Supreme      ┆ ["2 c.       ┆ squash       ┆ ["squash     ┆ ["squash",   ┆ {"Supreme    │
│        ┆ Squash       ┆ cooked and   ┆ casserole    ┆ (cooked,     ┆ "sour        ┆ Squash Casse │
│        ┆ Casserole    ┆ drained      ┆ with sour    ┆ drained)",   ┆ cream", …    ┆ role",["…    │
│        ┆              ┆ squa…        ┆ cre…         ┆ "…           ┆ "Ri…         ┆              │
│ 165730 ┆ Jello        ┆ ["1 large    ┆ lime jello   ┆ ["Cool       ┆ ["lime       ┆ {"Jello      │
│        ┆ Dessert (Or  ┆ Cool Whip",  ┆ salad with   ┆ Whip",       ┆ jello",      ┆ Dessert (Or  │
│        ┆ Green Goop)  ┆ "1 large…    ┆ cool whi…    ┆ "cottage     ┆ "Cool Whip", ┆ Green Goop…  │
│        ┆              ┆              ┆              ┆ cheese"…     ┆ … …          ┆              │
│ 175496 ┆ Crepes       ┆ ["6 eggs,    ┆ simple crepe ┆ ["eggs (well ┆ ["eggs",     ┆ {"Crepes",[" │
│        ┆              ┆ well         ┆ recipe with  ┆ beaten)",    ┆ "flour",     ┆ eggs",       │
│        ┆              ┆ beaten",     ┆ eggs …       ┆ "salt",…     ┆ "milk"]      ┆ "flour", "m… │
│        ┆              ┆ "1/2 t…      ┆              ┆              ┆              ┆              │
└────────┴──────────────┴──────────────┴──────────────┴──────────────┴──────────────┴──────────────┘

In [13]:
# Don't accidentally overwrite
#with open("../../data/eval_data/human_annotations.json", "w") as f:
#    json.dump(human_eval_ds.select('index', 'title', 'ingredients').to_dicts(), f, indent=2)

In [14]:
with open("../../data/eval_data/human_annotations.json", "r") as f:
    human_annotations_ds = pl.read_json(f)

In [15]:
human_annotations_ds.head()

shape: (5, 5)
┌────────┬──────────────────────┬──────────────────────┬─────────────────────┬─────────────────────┐
│ index  ┆ title                ┆ ingredients          ┆ human_ingredients   ┆ human_key_ingredien │
│ ---    ┆ ---                  ┆ ---                  ┆ ---                 ┆ ts                  │
│ i64    ┆ str                  ┆ list[str]            ┆ list[str]           ┆ ---                 │
│        ┆                      ┆                      ┆                     ┆ list[str]           │
╞════════╪══════════════════════╪══════════════════════╪═════════════════════╪═════════════════════╡
│ 25000  ┆ Pineapple Cream Cake ┆ ["1 pkg. white cake  ┆ ["cake mix",        ┆ ["two packages of   │
│        ┆                      ┆ mix", "2 s…          ┆ "pudding mix", … …  ┆ vanilla inst…       │
│ 135438 ┆ Pineapple Casserole  ┆ ["2 large cans       ┆ ["canned            ┆ ["grated cheddar    │
│        ┆                      ┆ pineapple tidbi…     ┆ pineapple",         ┆ cheese", "a p…      │
│        ┆                      ┆                      ┆ "flour", …          ┆                     │
│ 230315 ┆ Low-Fat Chili        ┆ ["1 1/2 lb. ground   ┆ ["ground turkey",   ┆ ["coarsely chopped  │
│        ┆                      ┆ turkey", "1…         ┆ "onion", … "…       ┆ tomatoes", …        │
│ 272288 ┆ Almond Bars          ┆ ["1 c. butter", "2   ┆ ["butter", "flour", ┆ ["butter", "flour", │
│        ┆                      ┆ c. flour", …         ┆ "powdered …         ┆ "powdered …         │
│ 275407 ┆ Pineapple Icebox     ┆ ["1 box yellow cake  ┆ ["yellow cake mix", ┆ ["a box of yellow   │
│        ┆ Cake                 ┆ mix", "1 (…          ┆ "can of pi…         ┆ cake mix", "…       │
└────────┴──────────────────────┴──────────────────────┴─────────────────────┴─────────────────────┘

In [16]:
human_eval_w_annotations_ds = human_eval_ds.with_columns(human_annotations_ds.select('human_ingredients'))
human_eval_w_annotations_ds = human_eval_w_annotations_ds.with_columns(human_annotations_ds.select('human_key_ingredients'))

In [17]:
human_eval_w_annotations_ds.head()

shape: (5, 9)
┌────────┬────────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ index  ┆ title      ┆ ingredient ┆ google_se ┆ … ┆ important ┆ google_se ┆ human_ing ┆ human_key │
│ ---    ┆ ---        ┆ s          ┆ arch_quer ┆   ┆ _ingredie ┆ arch_quer ┆ redients  ┆ _ingredie │
│ i64    ┆ str        ┆ ---        ┆ y         ┆   ┆ nts_for_s ┆ y_process ┆ ---       ┆ nts       │
│        ┆            ┆ list[str]  ┆ ---       ┆   ┆ ear…      ┆ ed        ┆ list[str] ┆ ---       │
│        ┆            ┆            ┆ str       ┆   ┆ ---       ┆ ---       ┆           ┆ list[str] │
│        ┆            ┆            ┆           ┆   ┆ list[str] ┆ struct[2] ┆           ┆           │
╞════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 42580  ┆ Asparagus- ┆ ["1 (3     ┆ asparagus ┆ … ┆ ["lime    ┆ {"Asparag ┆ ["cake    ┆ ["two     │
│        ┆ Cucumber   ┆ oz.) pkg.  ┆ cucumber  ┆   ┆ gelatin", ┆ us-Cucumb ┆ mix",     ┆ packages  │
│        ┆ Mold       ┆ lime       ┆ jello     ┆   ┆ "cream of ┆ er Mold", ┆ "pudding  ┆ of        │
│        ┆            ┆ flavored…  ┆ mold …    ┆   ┆ asp…      ┆ ["j…      ┆ mix", … … ┆ vanilla   │
│        ┆            ┆            ┆           ┆   ┆           ┆           ┆           ┆ inst…     │
│ 89070  ┆ Picnic     ┆ ["1 (16    ┆ picnic    ┆ … ┆ ["kidney  ┆ {"Picnic  ┆ ["canned  ┆ ["grated  │
│        ┆ Beans      ┆ oz.) can   ┆ beans     ┆   ┆ beans",   ┆ Beans",[" ┆ pineapple ┆ cheddar   │
│        ┆            ┆ kidney     ┆ recipe    ┆   ┆ "pork and ┆ bacon",   ┆ ",        ┆ cheese",  │
│        ┆            ┆ beans"…    ┆ with      ┆   ┆ bea…      ┆ "kid…     ┆ "flour",  ┆ "a p…     │
│        ┆            ┆            ┆ bacon…    ┆   ┆           ┆           ┆ …         ┆           │
│ 102340 ┆ Supreme    ┆ ["2 c.     ┆ squash    ┆ … ┆ ["squash" ┆ {"Supreme ┆ ["ground  ┆ ["coarsel │
│        ┆ Squash     ┆ cooked and ┆ casserole ┆   ┆ , "sour   ┆ Squash    ┆ turkey",  ┆ y chopped │
│        ┆ Casserole  ┆ drained    ┆ with sour ┆   ┆ cream", … ┆ Casserole ┆ "onion",  ┆ tomatoes" │
│        ┆            ┆ squa…      ┆ cre…      ┆   ┆ "Ri…      ┆ ",["…     ┆ … "…      ┆ , …       │
│ 165730 ┆ Jello      ┆ ["1 large  ┆ lime      ┆ … ┆ ["lime    ┆ {"Jello   ┆ ["butter" ┆ ["butter" │
│        ┆ Dessert    ┆ Cool       ┆ jello     ┆   ┆ jello",   ┆ Dessert   ┆ ,         ┆ ,         │
│        ┆ (Or Green  ┆ Whip", "1  ┆ salad     ┆   ┆ "Cool     ┆ (Or Green ┆ "flour",  ┆ "flour",  │
│        ┆ Goop)      ┆ large…     ┆ with cool ┆   ┆ Whip", …  ┆ Goop…     ┆ "powdered ┆ "powdered │
│        ┆            ┆            ┆ whi…      ┆   ┆ …         ┆           ┆ …         ┆ …         │
│ 175496 ┆ Crepes     ┆ ["6 eggs,  ┆ simple    ┆ … ┆ ["eggs",  ┆ {"Crepes" ┆ ["yellow  ┆ ["a box   │
│        ┆            ┆ well       ┆ crepe     ┆   ┆ "flour",  ┆ ,["eggs", ┆ cake      ┆ of yellow │
│        ┆            ┆ beaten",   ┆ recipe    ┆   ┆ "milk"]   ┆ "flour",  ┆ mix",     ┆ cake      │
│        ┆            ┆ "1/2 t…    ┆ with eggs ┆   ┆           ┆ "m…       ┆ "can of   ┆ mix", "…  │
│        ┆            ┆            ┆ …         ┆   ┆           ┆           ┆ pi…       ┆           │
└────────┴────────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [18]:
# Don't accidentally overwrite
#with open("../../data/eval_data/human_annot_eval.json", "w") as f:
#    json.dump(human_eval_w_annotations_ds.to_dicts(), f, indent=2)

In [19]:
non_eval_idx = [i for i in range(nlg_ds.shape[0]) if i not in eval_data_idx]

In [20]:
eval_10k_idx = list(set(random.sample(non_eval_idx, k=9000) + eval_data_idx))

In [23]:
with open("../../data/eval_data/eval_10k.json", "r") as f:
    read_eval_10k_ds = pl.read_json(f)

In [24]:
eval_10k_idx = read_eval_10k_ds['index'].to_numpy()

In [25]:
non_eval_100k_idx = np.delete(np.arange(nlg_ds.shape[0]), eval_10k_idx)

In [26]:
non_eval_100k_idx

array([      0,       1,       2, ..., 2231139, 2231140, 2231141],
      shape=(2221142,))

In [29]:
eval_100k_idx = list(set(random.sample(list(non_eval_100k_idx), k=90000) + list(eval_10k_idx)))

In [30]:
len(eval_100k_idx)

100000

In [24]:
eval_10k_ds = nlg_ds.filter(pl.col('index').is_in(eval_10k_idx))

In [25]:
# Don't accidentally overwrite
#with open("../../data/eval_data/eval_10k.json", "w") as f:
#    json.dump(eval_10k_ds.to_dicts(), f, indent=2)

In [32]:
eval_100k_ds = nlg_ds.filter(pl.col('index').is_in(eval_100k_idx))

In [33]:
# Don't accidentally overwrite
#with open("../../data/eval_data/eval_100k.json", "w") as f:
#    json.dump(eval_100k_ds.to_dicts(), f, indent=2)

### Sanity check that we can read data properly

In [34]:
with open("../../data/eval_data/eval_100k.json", "r") as f:
    read_eval_100k_ds = pl.read_json(f)

In [35]:
(eval_100k_ds == read_eval_100k_ds).filter(pl.col('title') == False)

shape: (0, 8)
┌──────┬───────┬─────────────┬────────────┬──────┬────────┬──────┬───────┐
│      ┆ title ┆ ingredients ┆ directions ┆ link ┆ source ┆ NER  ┆ index │
│ ---  ┆ ---   ┆ ---         ┆ ---        ┆ ---  ┆ ---    ┆ ---  ┆ ---   │
│ bool ┆ bool  ┆ bool        ┆ bool       ┆ bool ┆ bool   ┆ bool ┆ bool  │
╞══════╪═══════╪═════════════╪════════════╪══════╪════════╪══════╪═══════╡
└──────┴───────┴─────────────┴────────────┴──────┴────────┴──────┴───────┘

## Generate 150 datapoint for labeling that is not in any of our evaluation data

In [36]:
import numpy as np

In [37]:
eval_100k_idx = read_eval_100k_ds['index'].to_numpy()

In [38]:
eval_100k_idx

array([     64,      83,      88, ..., 2231086, 2231122, 2231137],
      shape=(100000,))

In [39]:
non_100k_idx = np.delete(np.arange(nlg_ds.shape[0]), eval_100k_idx)

In [40]:
np.arange(nlg_ds.shape[0])

array([      0,       1,       2, ..., 2231139, 2231140, 2231141],
      shape=(2231142,))

In [41]:
non_100k_idx

array([      0,       1,       2, ..., 2231139, 2231140, 2231141],
      shape=(2131142,))

In [46]:
label_150_idx = np.array(list(set(random.sample(list(non_100k_idx), k=150))))

In [50]:
label_150_idx.sort()

In [51]:
label_150_idx

array([  41254,   42099,   60699,   61742,   62233,   63247,   91437,
        109467,  146606,  150425,  150466,  185269,  192495,  196691,
        197970,  204596,  218859,  225014,  229259,  278795,  297220,
        317376,  319738,  346087,  364271,  371377,  375769,  379518,
        386200,  391990,  398235,  417520,  422987,  496661,  510940,
        526801,  552638,  580596,  589713,  594672,  600311,  600478,
        631618,  643177,  659740,  683934,  691275,  703046,  707281,
        730945,  735990,  764118,  801349,  820061,  823725,  826954,
        831303,  851295,  874570,  896740,  909353,  913607,  921543,
        923317,  937613,  972310,  991333, 1034874, 1042441, 1043965,
       1081875, 1112769, 1129356, 1158262, 1185614, 1189029, 1196358,
       1210700, 1214587, 1214662, 1221175, 1228520, 1231000, 1232842,
       1244642, 1252446, 1256357, 1259675, 1260661, 1265192, 1268011,
       1297789, 1304555, 1316825, 1352016, 1354643, 1358229, 1390880,
       1392526, 1405

In [52]:
label_150_ds = nlg_ds.filter(pl.col('index').is_in(label_150_idx))

In [54]:
i = 0
labels = []
for index, ingredients in label_150_ds['index', 'ingredients'].iter_rows():
    out_obj= {}
    text = "\n".join(ingredients)
    out_obj = {
        "data": {
            "id": index,
            "text": text
        },
    }
    labels.append(out_obj)

In [59]:
with open('../../data/NER_data/recipeNLG_to_label.json', mode='w') as f:
    json.dump(labels, f)

In [71]:
for i in label_150_ds.filter(pl.col('index') == 1297789)['ingredients'][0]:
    print(i)

2 pounds medium red-skinned potatoes
scrubbed Sea salt 1 pound skinless wild salmon fillet Safflower or sunflower oil
for greasing and frying Freshly ground pepper 1 bunch scallions (about 6 scallions)
coarsely chopped 3 large eggs
lightly beaten 3 garlic cloves
minced 2 tablespoons minced fresh ginger 1/2 medium red onion
finely chopped 1 tablespoon tamari 1 tablespoon toasted sesame oil 1/2 cup plain dry bread crumbs Dill Sauce
for serving
