In [1]:
import random
import polars as pl
from pathlib import Path
import json

In [2]:
nlg_ds = pl.read_csv('../../data/recipenlg/RecipeNLG_dataset.csv')#,  n_rows=1000)
nlg_ds = nlg_ds.with_columns(pl.col("ingredients").str.json_decode())
nlg_ds = nlg_ds.with_columns(pl.col("directions").str.json_decode())
nlg_ds = nlg_ds.with_columns(pl.arange(pl.len()).alias("index"))

In [3]:
import random
random.seed(123)
eval_data_idx = random.sample(range(0,nlg_ds.shape[0]), k=1000)

### The above code was used to generate data, but now since it is generated, we use the exact indexes in the generated data

In [4]:
with open("../../data/eval_data/eval_data.json", 'r') as f:
    read_idx_ds = pl.read_json(f)

In [5]:
eval_data_idx = list(read_idx_ds['index'])

In [6]:
out_ds = nlg_ds.filter(pl.col("index").is_in(eval_data_idx))

In [7]:
# Don't accidentally overwrite
#with open("../../data/eval_data/eval_data.json", "w") as f:
    #json.dump(out_ds.select('index', 'title', 'ingredients').to_dicts(), f, indent=2)

In [8]:
with open("../../data/eval_data/processed_data.json", "r") as f:
    processed_ds = pl.read_json(f)

In [9]:
processed_ds.head()

shape: (5, 7)
┌───────┬───────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┐
│ index ┆ title         ┆ ingredients  ┆ google_searc ┆ main_food_it ┆ important_in ┆ google_searc │
│ ---   ┆ ---           ┆ ---          ┆ h_query      ┆ ems_and_prep ┆ gredients_fo ┆ h_query_proc │
│ i64   ┆ str           ┆ list[str]    ┆ ---          ┆ aratio…      ┆ r_sear…      ┆ essed        │
│       ┆               ┆              ┆ str          ┆ ---          ┆ ---          ┆ ---          │
│       ┆               ┆              ┆              ┆ list[str]    ┆ list[str]    ┆ struct[2]    │
╞═══════╪═══════════════╪══════════════╪══════════════╪══════════════╪══════════════╪══════════════╡
│ 1461  ┆ Apricot Cake  ┆ ["2 c.       ┆ apricot cake ┆ ["sugar",    ┆ ["apricot    ┆ {"Apricot    │
│       ┆               ┆ sugar", "4   ┆ recipe with  ┆ "eggs", …    ┆ baby food",  ┆ Cake",["baby │
│       ┆               ┆ eggs", …     ┆ baby …       ┆ "chopped n…  ┆ "flour",…    ┆ food", …     │
│       ┆               ┆ "1/…         ┆              ┆              ┆              ┆              │
│ 1490  ┆ Angel         ┆ ["1 c.       ┆ angel        ┆ ["miniature  ┆ ["marshmallo ┆ {"Angel Deli │
│       ┆ Delights      ┆ miniature    ┆ delights     ┆ marshmallows ┆ ws",         ┆ ghts",["mars │
│       ┆               ┆ marshmallows ┆ recipe with  ┆ ", "br…      ┆ "pretzels",  ┆ hmallo…      │
│       ┆               ┆ "…           ┆ mar…         ┆              ┆ ……           ┆              │
│ 3374  ┆ Savory        ┆ ["1 lb. bulk ┆ sausage and  ┆ ["bulk pork  ┆ ["pork       ┆ {"Savory     │
│       ┆ Sausage       ┆ pork         ┆ rice         ┆ sausage",    ┆ sausage",    ┆ Sausage Cass │
│       ┆ Casserole     ┆ sausage",    ┆ casserole    ┆ "uncooke…    ┆ "rice", …    ┆ erole",["…   │
│       ┆               ┆ "1…          ┆ wit…         ┆              ┆ "al…         ┆              │
│ 7006  ┆ Zemakove      ┆ ["2 c.       ┆ potato       ┆ ["mashed     ┆ ["mashed     ┆ {"Zemakove   │
│       ┆ Knedliky A    ┆ mashed       ┆ dumplings    ┆ potatoes",   ┆ potatoes",   ┆ Knedliky A   │
│       ┆ Kysele Zel…   ┆ potatoes",   ┆ with         ┆ "salt", … …  ┆ "sauerkrau…  ┆ Kysele Z…    │
│       ┆               ┆ "1/2 …       ┆ sauerkra…    ┆              ┆              ┆              │
│ 9957  ┆ Scalloped     ┆ ["1/4 c.     ┆ scalloped    ┆ ["sugar",    ┆ ["sweet      ┆ {"Scalloped  │
│       ┆ Sweet         ┆ sugar", "1/2 ┆ sweet        ┆ "cinnamon",  ┆ potatoes",   ┆ Sweet Potato │
│       ┆ Potatoes      ┆ tsp. cin…    ┆ potatoes and ┆ … "marga…    ┆ "apples", "… ┆ es",["…      │
│       ┆               ┆              ┆ a…           ┆              ┆              ┆              │
└───────┴───────────────┴──────────────┴──────────────┴──────────────┴──────────────┴──────────────┘

In [10]:
human_eval_data_idx = random.sample(eval_data_idx, k=50)

In [11]:
human_eval_ds = processed_ds.filter(pl.col("index").is_in(human_eval_data_idx))

In [12]:
human_eval_ds.head()

shape: (5, 7)
┌────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┐
│ index  ┆ title        ┆ ingredients  ┆ google_searc ┆ main_food_it ┆ important_in ┆ google_searc │
│ ---    ┆ ---          ┆ ---          ┆ h_query      ┆ ems_and_prep ┆ gredients_fo ┆ h_query_proc │
│ i64    ┆ str          ┆ list[str]    ┆ ---          ┆ aratio…      ┆ r_sear…      ┆ essed        │
│        ┆              ┆              ┆ str          ┆ ---          ┆ ---          ┆ ---          │
│        ┆              ┆              ┆              ┆ list[str]    ┆ list[str]    ┆ struct[2]    │
╞════════╪══════════════╪══════════════╪══════════════╪══════════════╪══════════════╪══════════════╡
│ 42580  ┆ Asparagus-Cu ┆ ["1 (3 oz.)  ┆ asparagus    ┆ ["lime       ┆ ["lime       ┆ {"Asparagus- │
│        ┆ cumber Mold  ┆ pkg. lime    ┆ cucumber     ┆ flavored     ┆ gelatin",    ┆ Cucumber     │
│        ┆              ┆ flavored…    ┆ jello mold … ┆ gelatin",    ┆ "cream of    ┆ Mold",["j…   │
│        ┆              ┆              ┆              ┆ "boi…        ┆ asp…         ┆              │
│ 89070  ┆ Picnic Beans ┆ ["1 (16 oz.) ┆ picnic beans ┆ ["kidney     ┆ ["kidney     ┆ {"Picnic Bea │
│        ┆              ┆ can kidney   ┆ recipe with  ┆ beans",      ┆ beans",      ┆ ns",["bacon" │
│        ┆              ┆ beans"…      ┆ bacon…       ┆ "pork and    ┆ "pork and    ┆ , "kid…      │
│        ┆              ┆              ┆              ┆ bea…         ┆ bea…         ┆              │
│ 102340 ┆ Supreme      ┆ ["2 c.       ┆ squash       ┆ ["squash     ┆ ["squash",   ┆ {"Supreme    │
│        ┆ Squash       ┆ cooked and   ┆ casserole    ┆ (cooked,     ┆ "sour        ┆ Squash Casse │
│        ┆ Casserole    ┆ drained      ┆ with sour    ┆ drained)",   ┆ cream", …    ┆ role",["…    │
│        ┆              ┆ squa…        ┆ cre…         ┆ "…           ┆ "Ri…         ┆              │
│ 165730 ┆ Jello        ┆ ["1 large    ┆ lime jello   ┆ ["Cool       ┆ ["lime       ┆ {"Jello      │
│        ┆ Dessert (Or  ┆ Cool Whip",  ┆ salad with   ┆ Whip",       ┆ jello",      ┆ Dessert (Or  │
│        ┆ Green Goop)  ┆ "1 large…    ┆ cool whi…    ┆ "cottage     ┆ "Cool Whip", ┆ Green Goop…  │
│        ┆              ┆              ┆              ┆ cheese"…     ┆ … …          ┆              │
│ 175496 ┆ Crepes       ┆ ["6 eggs,    ┆ simple crepe ┆ ["eggs (well ┆ ["eggs",     ┆ {"Crepes",[" │
│        ┆              ┆ well         ┆ recipe with  ┆ beaten)",    ┆ "flour",     ┆ eggs",       │
│        ┆              ┆ beaten",     ┆ eggs …       ┆ "salt",…     ┆ "milk"]      ┆ "flour", "m… │
│        ┆              ┆ "1/2 t…      ┆              ┆              ┆              ┆              │
└────────┴──────────────┴──────────────┴──────────────┴──────────────┴──────────────┴──────────────┘

In [13]:
# Don't accidentally overwrite
#with open("../../data/eval_data/human_annotations.json", "w") as f:
#    json.dump(human_eval_ds.select('index', 'title', 'ingredients').to_dicts(), f, indent=2)

In [14]:
with open("../../data/eval_data/human_annotations.json", "r") as f:
    human_annotations_ds = pl.read_json(f)

In [15]:
human_annotations_ds.head()

shape: (5, 5)
┌────────┬──────────────────────┬──────────────────────┬─────────────────────┬─────────────────────┐
│ index  ┆ title                ┆ ingredients          ┆ human_ingredients   ┆ human_key_ingredien │
│ ---    ┆ ---                  ┆ ---                  ┆ ---                 ┆ ts                  │
│ i64    ┆ str                  ┆ list[str]            ┆ list[str]           ┆ ---                 │
│        ┆                      ┆                      ┆                     ┆ list[str]           │
╞════════╪══════════════════════╪══════════════════════╪═════════════════════╪═════════════════════╡
│ 25000  ┆ Pineapple Cream Cake ┆ ["1 pkg. white cake  ┆ ["cake mix",        ┆ ["two packages of   │
│        ┆                      ┆ mix", "2 s…          ┆ "pudding mix", … …  ┆ vanilla inst…       │
│ 135438 ┆ Pineapple Casserole  ┆ ["2 large cans       ┆ ["canned            ┆ ["grated cheddar    │
│        ┆                      ┆ pineapple tidbi…     ┆ pineapple",         ┆ cheese", "a p…      │
│        ┆                      ┆                      ┆ "flour", …          ┆                     │
│ 230315 ┆ Low-Fat Chili        ┆ ["1 1/2 lb. ground   ┆ ["ground turkey",   ┆ ["coarsely chopped  │
│        ┆                      ┆ turkey", "1…         ┆ "onion", … "…       ┆ tomatoes", …        │
│ 272288 ┆ Almond Bars          ┆ ["1 c. butter", "2   ┆ ["butter", "flour", ┆ ["butter", "flour", │
│        ┆                      ┆ c. flour", …         ┆ "powdered …         ┆ "powdered …         │
│ 275407 ┆ Pineapple Icebox     ┆ ["1 box yellow cake  ┆ ["yellow cake mix", ┆ ["a box of yellow   │
│        ┆ Cake                 ┆ mix", "1 (…          ┆ "can of pi…         ┆ cake mix", "…       │
└────────┴──────────────────────┴──────────────────────┴─────────────────────┴─────────────────────┘

In [16]:
human_eval_w_annotations_ds = human_eval_ds.with_columns(human_annotations_ds.select('human_ingredients'))
human_eval_w_annotations_ds = human_eval_w_annotations_ds.with_columns(human_annotations_ds.select('human_key_ingredients'))

In [17]:
human_eval_w_annotations_ds.head()

shape: (5, 9)
┌────────┬────────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ index  ┆ title      ┆ ingredient ┆ google_se ┆ … ┆ important ┆ google_se ┆ human_ing ┆ human_key │
│ ---    ┆ ---        ┆ s          ┆ arch_quer ┆   ┆ _ingredie ┆ arch_quer ┆ redients  ┆ _ingredie │
│ i64    ┆ str        ┆ ---        ┆ y         ┆   ┆ nts_for_s ┆ y_process ┆ ---       ┆ nts       │
│        ┆            ┆ list[str]  ┆ ---       ┆   ┆ ear…      ┆ ed        ┆ list[str] ┆ ---       │
│        ┆            ┆            ┆ str       ┆   ┆ ---       ┆ ---       ┆           ┆ list[str] │
│        ┆            ┆            ┆           ┆   ┆ list[str] ┆ struct[2] ┆           ┆           │
╞════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 42580  ┆ Asparagus- ┆ ["1 (3     ┆ asparagus ┆ … ┆ ["lime    ┆ {"Asparag ┆ ["cake    ┆ ["two     │
│        ┆ Cucumber   ┆ oz.) pkg.  ┆ cucumber  ┆   ┆ gelatin", ┆ us-Cucumb ┆ mix",     ┆ packages  │
│        ┆ Mold       ┆ lime       ┆ jello     ┆   ┆ "cream of ┆ er Mold", ┆ "pudding  ┆ of        │
│        ┆            ┆ flavored…  ┆ mold …    ┆   ┆ asp…      ┆ ["j…      ┆ mix", … … ┆ vanilla   │
│        ┆            ┆            ┆           ┆   ┆           ┆           ┆           ┆ inst…     │
│ 89070  ┆ Picnic     ┆ ["1 (16    ┆ picnic    ┆ … ┆ ["kidney  ┆ {"Picnic  ┆ ["canned  ┆ ["grated  │
│        ┆ Beans      ┆ oz.) can   ┆ beans     ┆   ┆ beans",   ┆ Beans",[" ┆ pineapple ┆ cheddar   │
│        ┆            ┆ kidney     ┆ recipe    ┆   ┆ "pork and ┆ bacon",   ┆ ",        ┆ cheese",  │
│        ┆            ┆ beans"…    ┆ with      ┆   ┆ bea…      ┆ "kid…     ┆ "flour",  ┆ "a p…     │
│        ┆            ┆            ┆ bacon…    ┆   ┆           ┆           ┆ …         ┆           │
│ 102340 ┆ Supreme    ┆ ["2 c.     ┆ squash    ┆ … ┆ ["squash" ┆ {"Supreme ┆ ["ground  ┆ ["coarsel │
│        ┆ Squash     ┆ cooked and ┆ casserole ┆   ┆ , "sour   ┆ Squash    ┆ turkey",  ┆ y chopped │
│        ┆ Casserole  ┆ drained    ┆ with sour ┆   ┆ cream", … ┆ Casserole ┆ "onion",  ┆ tomatoes" │
│        ┆            ┆ squa…      ┆ cre…      ┆   ┆ "Ri…      ┆ ",["…     ┆ … "…      ┆ , …       │
│ 165730 ┆ Jello      ┆ ["1 large  ┆ lime      ┆ … ┆ ["lime    ┆ {"Jello   ┆ ["butter" ┆ ["butter" │
│        ┆ Dessert    ┆ Cool       ┆ jello     ┆   ┆ jello",   ┆ Dessert   ┆ ,         ┆ ,         │
│        ┆ (Or Green  ┆ Whip", "1  ┆ salad     ┆   ┆ "Cool     ┆ (Or Green ┆ "flour",  ┆ "flour",  │
│        ┆ Goop)      ┆ large…     ┆ with cool ┆   ┆ Whip", …  ┆ Goop…     ┆ "powdered ┆ "powdered │
│        ┆            ┆            ┆ whi…      ┆   ┆ …         ┆           ┆ …         ┆ …         │
│ 175496 ┆ Crepes     ┆ ["6 eggs,  ┆ simple    ┆ … ┆ ["eggs",  ┆ {"Crepes" ┆ ["yellow  ┆ ["a box   │
│        ┆            ┆ well       ┆ crepe     ┆   ┆ "flour",  ┆ ,["eggs", ┆ cake      ┆ of yellow │
│        ┆            ┆ beaten",   ┆ recipe    ┆   ┆ "milk"]   ┆ "flour",  ┆ mix",     ┆ cake      │
│        ┆            ┆ "1/2 t…    ┆ with eggs ┆   ┆           ┆ "m…       ┆ "can of   ┆ mix", "…  │
│        ┆            ┆            ┆ …         ┆   ┆           ┆           ┆ pi…       ┆           │
└────────┴────────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [18]:
# Don't accidentally overwrite
#with open("../../data/eval_data/human_annot_eval.json", "w") as f:
#    json.dump(human_eval_w_annotations_ds.to_dicts(), f, indent=2)

In [19]:
non_eval_idx = [i for i in range(nlg_ds.shape[0]) if i not in eval_data_idx]

In [20]:
eval_10k_idx = list(set(random.sample(non_eval_idx, k=9000) + eval_data_idx))

In [23]:
with open("../../data/eval_data/eval_10k.json", "r") as f:
    read_eval_10k_ds = pl.read_json(f)

In [24]:
eval_10k_idx = read_eval_10k_ds['index'].to_numpy()

In [25]:
non_eval_100k_idx = np.delete(np.arange(nlg_ds.shape[0]), eval_10k_idx)

In [26]:
non_eval_100k_idx

array([      0,       1,       2, ..., 2231139, 2231140, 2231141],
      shape=(2221142,))

In [29]:
eval_100k_idx = list(set(random.sample(list(non_eval_100k_idx), k=90000) + list(eval_10k_idx)))

In [30]:
len(eval_100k_idx)

100000

In [24]:
eval_10k_ds = nlg_ds.filter(pl.col('index').is_in(eval_10k_idx))

In [25]:
# Don't accidentally overwrite
#with open("../../data/eval_data/eval_10k.json", "w") as f:
#    json.dump(eval_10k_ds.to_dicts(), f, indent=2)

In [32]:
eval_100k_ds = nlg_ds.filter(pl.col('index').is_in(eval_100k_idx))

In [33]:
# Don't accidentally overwrite
#with open("../../data/eval_data/eval_100k.json", "w") as f:
#    json.dump(eval_100k_ds.to_dicts(), f, indent=2)

### Sanity check that we can read data properly

In [34]:
with open("../../data/eval_data/eval_100k.json", "r") as f:
    read_eval_100k_ds = pl.read_json(f)

In [35]:
(eval_100k_ds == read_eval_100k_ds).filter(pl.col('title') == False)

shape: (0, 8)
┌──────┬───────┬─────────────┬────────────┬──────┬────────┬──────┬───────┐
│      ┆ title ┆ ingredients ┆ directions ┆ link ┆ source ┆ NER  ┆ index │
│ ---  ┆ ---   ┆ ---         ┆ ---        ┆ ---  ┆ ---    ┆ ---  ┆ ---   │
│ bool ┆ bool  ┆ bool        ┆ bool       ┆ bool ┆ bool   ┆ bool ┆ bool  │
╞══════╪═══════╪═════════════╪════════════╪══════╪════════╪══════╪═══════╡
└──────┴───────┴─────────────┴────────────┴──────┴────────┴──────┴───────┘

## Generate 150 datapoint for labeling that is not in any of our evaluation data

In [36]:
import numpy as np

In [37]:
eval_100k_idx = read_eval_100k_ds['index'].to_numpy()

In [38]:
eval_100k_idx

array([     64,      83,      88, ..., 2231086, 2231122, 2231137],
      shape=(100000,))

In [39]:
non_100k_idx = np.delete(np.arange(nlg_ds.shape[0]), eval_100k_idx)

In [40]:
np.arange(nlg_ds.shape[0])

array([      0,       1,       2, ..., 2231139, 2231140, 2231141],
      shape=(2231142,))

In [41]:
non_100k_idx

array([      0,       1,       2, ..., 2231139, 2231140, 2231141],
      shape=(2131142,))

In [46]:
label_150_idx = np.array(list(set(random.sample(list(non_100k_idx), k=150))))

In [50]:
label_150_idx.sort()

In [51]:
label_150_idx

array([  41254,   42099,   60699,   61742,   62233,   63247,   91437,
        109467,  146606,  150425,  150466,  185269,  192495,  196691,
        197970,  204596,  218859,  225014,  229259,  278795,  297220,
        317376,  319738,  346087,  364271,  371377,  375769,  379518,
        386200,  391990,  398235,  417520,  422987,  496661,  510940,
        526801,  552638,  580596,  589713,  594672,  600311,  600478,
        631618,  643177,  659740,  683934,  691275,  703046,  707281,
        730945,  735990,  764118,  801349,  820061,  823725,  826954,
        831303,  851295,  874570,  896740,  909353,  913607,  921543,
        923317,  937613,  972310,  991333, 1034874, 1042441, 1043965,
       1081875, 1112769, 1129356, 1158262, 1185614, 1189029, 1196358,
       1210700, 1214587, 1214662, 1221175, 1228520, 1231000, 1232842,
       1244642, 1252446, 1256357, 1259675, 1260661, 1265192, 1268011,
       1297789, 1304555, 1316825, 1352016, 1354643, 1358229, 1390880,
       1392526, 1405

In [52]:
label_150_ds = nlg_ds.filter(pl.col('index').is_in(label_150_idx))

In [54]:
i = 0
labels = []
for index, ingredients in label_150_ds['index', 'ingredients'].iter_rows():
    out_obj= {}
    text = "\n".join(ingredients)
    out_obj = {
        "data": {
            "id": index,
            "text": text
        },
    }
    labels.append(out_obj)

In [59]:
with open('../../data/NER_data/recipeNLG_to_label.json', mode='w') as f:
    json.dump(labels, f)

In [71]:
for i in label_150_ds.filter(pl.col('index') == 1297789)['ingredients'][0]:
    print(i)

2 pounds medium red-skinned potatoes
scrubbed Sea salt 1 pound skinless wild salmon fillet Safflower or sunflower oil
for greasing and frying Freshly ground pepper 1 bunch scallions (about 6 scallions)
coarsely chopped 3 large eggs
lightly beaten 3 garlic cloves
minced 2 tablespoons minced fresh ginger 1/2 medium red onion
finely chopped 1 tablespoon tamari 1 tablespoon toasted sesame oil 1/2 cup plain dry bread crumbs Dill Sauce
for serving


In [73]:
import pandas as pd

In [134]:
def remove_units(ds):
    new_annotations = []
    for i, [data, annotation] in ds[['data', 'annotations']].iterrows():
        text = data['text']
        new_text = text
        removed_amt = 0
        new_annotation_data = []
        annotation_data = annotation[0]['result']
        remove_next = False
        last_start = -1
        for annotation in annotation_data:
            value = annotation['value']
            label = value['labels'][0]
            start = value['start']
            end = value['end']
            if remove_next:
                new_text = new_text[:last_start-removed_amt] + new_text[start-removed_amt:]
                removed_amt += start - last_start
                remove_next = False
            if label == 'Quantity' or  label == 'Unit':
                remove_next = True
                last_start = start
            else:
                new_value = value
                new_value['start'] = start - removed_amt
                new_value['end'] = end - removed_amt
                new_annotation_data.append(new_value)
        new_annotations.append((text, new_annotation_data))
    return new_annotations

In [135]:
new_an = remove_units(ner_ds)

[('5 ounces rum\n4 ounces triple sec\n3 ounces Tia Maria\n20 ounces orange juice\n',
  [{'start': 0, 'end': 3, 'text': 'rum', 'labels': ['Food']},
   {'start': 4, 'end': 14, 'text': 'triple sec', 'labels': ['Food']},
   {'start': 15, 'end': 24, 'text': 'Tia Maria', 'labels': ['Food']},
   {'start': 25, 'end': 37, 'text': 'orange juice', 'labels': ['Food']}]),
 ('2 tubes cinnamon roll, refrigerated, with icing\n4 tablespoons butter, melted\n6 eggs\n½ cup milk\n2 teaspoons cinnamon\n2 teaspoons vanilla\n1 cup maple syrup\n',
  [{'start': 0, 'end': 13, 'text': 'cinnamon roll', 'labels': ['Food']},
   {'start': 15, 'end': 27, 'text': 'refrigerated', 'labels': ['Alteration']},
   {'start': 34, 'end': 39, 'text': 'icing', 'labels': ['Food']},
   {'start': 40, 'end': 46, 'text': 'butter', 'labels': ['Food']},
   {'start': 48, 'end': 54, 'text': 'melted', 'labels': ['Alteration']},
   {'start': 55, 'end': 59, 'text': 'eggs', 'labels': ['Food']},
   {'start': 60, 'end': 64, 'text': 'milk', 'lab

In [111]:
ner_ds.head()

id                                        annotations  \
0   1  [{'id': 2, 'completed_by': 1, 'result': [{'val...   
1   2  [{'id': 3, 'completed_by': 1, 'result': [{'val...   
2   3  [{'id': 4, 'completed_by': 1, 'result': [{'val...   
3   4  [{'id': 5, 'completed_by': 1, 'result': [{'val...   
4   5  [{'id': 6, 'completed_by': 1, 'result': [{'val...   

                      file_upload drafts predictions  \
0  2249c960-label_s_tasteset.json     []         [1]   
1  2249c960-label_s_tasteset.json     []         [2]   
2  2249c960-label_s_tasteset.json     []         [3]   
3  2249c960-label_s_tasteset.json     []         [4]   
4  2249c960-label_s_tasteset.json     []         [5]   

                                                data meta  \
0  {'id': 2101, 'text': '5 ounces rum
4 ounces tr...   {}   
1  {'id': 2102, 'text': '2 tubes cinnamon roll, r...   {}   
2  {'id': 2103, 'text': '4 ripe coconuts
1 cup ev...   {}   
3  {'id': 2104, 'text': '1 sheet graham cracker (...   {}   
4  {'id': 2105, 'text': '1 (8 ounce) package cres...   {}   

                        created_at                       updated_at  inner_id  \
0 2025-05-14 14:24:58.753961+00:00 2025-05-14 14:25:08.674942+00:00         1   
1 2025-05-14 14:24:58.754033+00:00 2025-05-14 14:29:18.588099+00:00         2   
2 2025-05-14 14:24:58.754070+00:00 2025-05-14 14:30:25.910344+00:00         3   
3 2025-05-14 14:24:58.754104+00:00 2025-05-14 14:31:26.031006+00:00         4   
4 2025-05-14 14:24:58.754139+00:00 2025-05-14 14:32:23.664759+00:00         5   

   total_annotations  cancelled_annotations  total_predictions  comment_count  \
0                  1                      0                  1              0   
1                  1                      0                  1              0   
2                  1                      0                  1              0   
3                  1                      0                  1              0   
4                  1                      0                  1              0   

   unresolved_comment_count last_comment_updated_at  project  updated_by  \
0                         0                     NaT        1           1   
1                         0                     NaT        1           1   
2                         0                     NaT        1           1   
3                         0                     NaT        1           1   
4                         0                     NaT        1           1   

  comment_authors  
0              []  
1              []  
2              []  
3              []  
4              []

In [77]:
data['text']

'1 tablespoon unsalted butter\n4 cups water\n2 teaspoons salt\n2 1/4 cups yellow cornmeal\n1/4 cup heavy cream\n1 teaspoon dried thyme\nCooking spray\n2 tablespoons olive oil\n1/4 pound pancetta, chopped\n3 garlic cloves, minced\n1/2 teaspoon red pepper flakes\n1 (14-ounce) can diced tomatoes\n1 pound large shrimp, peeled and deveined\n3/4 teaspoon salt\n1 tablespoon chopped fresh flat-leaf parsley'

In [76]:
annotation_entities

[(0, 1, 'Quantity'),
 (2, 12, 'Unit'),
 (13, 21, 'Variety'),
 (22, 28, 'Food'),
 (29, 30, 'Quantity'),
 (31, 35, 'Unit'),
 (36, 41, 'Food'),
 (42, 43, 'Quantity'),
 (44, 53, 'Unit'),
 (54, 58, 'Food'),
 (59, 64, 'Quantity'),
 (65, 69, 'Unit'),
 (70, 76, 'Variety'),
 (77, 85, 'Food'),
 (86, 89, 'Quantity'),
 (90, 93, 'Unit'),
 (94, 105, 'Food'),
 (106, 107, 'Quantity'),
 (108, 116, 'Unit'),
 (117, 122, 'Preparation'),
 (123, 128, 'Food'),
 (129, 142, 'Food'),
 (143, 144, 'Quantity'),
 (145, 156, 'Unit'),
 (157, 166, 'Food'),
 (167, 170, 'Quantity'),
 (171, 176, 'Unit'),
 (177, 185, 'Food'),
 (187, 194, 'Preparation'),
 (195, 196, 'Quantity'),
 (197, 203, 'Food'),
 (204, 210, 'Unit'),
 (212, 218, 'Preparation'),
 (219, 222, 'Quantity'),
 (223, 231, 'Unit'),
 (232, 235, 'Variety'),
 (236, 249, 'Food'),
 (250, 251, 'Quantity'),
 (253, 261, 'Quantity'),
 (263, 266, 'Unit'),
 (267, 272, 'Preparation'),
 (273, 281, 'Food'),
 (282, 283, 'Quantity'),
 (284, 289, 'Unit'),
 (290, 295, 'State'),
 